// src/styles/appStyles.js

export const styles = {
  appWrapper: { minHeight: "100vh", width: "100vw", backgroundColor: "#f3f6f9", color: "#334155", fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', display: "flex", flexDirection: "column", boxSizing: "border-box" },
  loginPage: { minHeight: "100vh", width: "100vw", backgroundColor: "#0a255c", display: "flex", justifyContent: "center", alignItems: "center" },
  loginCard: { width: "420px", backgroundColor: "#ffffff", padding: "44px", borderRadius: "16px", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.35)" },
  topBar: { height: "74px", backgroundColor: "#ffffff", borderBottom: "1px solid #e2e8f0", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0 40px", position: "sticky", top: 0, zIndex: 100, boxSizing: "border-box", boxShadow: "0 4px 6px -1px rgba(10,37,92,0.02)" },
  tabItem: { height: "100%", padding: "0 24px", border: "none", backgroundColor: "transparent", cursor: "pointer", fontSize: "14px", display: "flex", alignItems: "center", transition: "all 0.15s ease", letterSpacing: "-0.1px" },
  userProfileBadge: { display: "flex", flexDirection: "column", fontSize: "11px", textAlign: "right" },
  logoutButton: { padding: "8px 18px", backgroundColor: "#ffffff", border: "1px solid #dcdfe4", borderRadius: "8px", color: "#475569", fontSize: "12px", fontWeight: "600", cursor: "pointer", transition: "all 0.2s", boxShadow: "0 1px 2px rgba(0,0,0,0.05)" },
  contentArea: { padding: "36px 40px", flexGrow: 1, display: "flex", flexDirection: "column", boxSizing: "border-box" },
  workspaceContainer: { width: "100%", display: "flex", flexDirection: "column" },
  fieldLabel: { display: "block", fontSize: "11px", textTransform: "uppercase", color: "#0a255c", fontWeight: "700", marginBottom: "6px", letterSpacing: "0.5px" },
  textInput: { width: "100%", maxWidth: "360px", padding: "11px 16px", backgroundColor: "#ffffff", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "13px", color: "#0f172a", outline: "none", boxShadow: "inset 0 1px 2px rgba(0,0,0,0.02)" },
  loginInput: { width: "100%", padding: "12px 16px", backgroundColor: "#ffffff", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "14px", boxSizing: "border-box", marginBottom: "12px" },
  loginSelect: { width: "100%", padding: "12px 16px", backgroundColor: "#ffffff", border: "1px solid #cbd5e1", borderRadius: "8px", fontSize: "14px", cursor: "pointer", boxSizing: "border-box", marginBottom: "12px" },
  submitButton: { padding: "11px 24px", backgroundColor: "#0a255c", border: "none", color: "#ffffff", fontWeight: "600", borderRadius: "8px", cursor: "pointer", fontSize: "13px", boxShadow: "0 4px 6px -1px rgba(10,37,92,0.2)", transition: "all 0.2s" },
  panel: { backgroundColor: "#ffffff", border: "1px solid #e5e9f0", borderRadius: "12px", padding: "28px", boxSizing: "border-box", boxShadow: "0 10px 25px -5px rgba(10,37,92,0.03), 0 8px 10px -6px rgba(10,37,92,0.03)" },
  table: { width: "100%", borderCollapse: "collapse", textAlign: "left" },
  thRow: { backgroundColor: "#f8fafc", borderBottom: "2px solid #e6f0fa" },
  th: { padding: "16px 20px", fontSize: "11px", color: "#0a255c", fontWeight: "700", textTransform: "uppercase", letterSpacing: "0.75px" },
  tr: { borderBottom: "1px solid #f0f4f8", transition: "background-color 0.15s ease" },
  td: { padding: "16px 20px", fontSize: "14px", color: "#334155" },
  badge: { padding: "6px 12px", borderRadius: "6px", fontSize: "12px", fontWeight: "700" },
  actionInlineBtn: { padding: "7px 16px", backgroundColor: "#e6f0fa", border: "1px solid #b3d1ff", borderRadius: "8px", color: "#0066cc", fontWeight: "700", fontSize: "12px", cursor: "pointer" },
  toggleStatusButton: { padding: "6px 14px", borderRadius: "8px", fontWeight: "700", fontSize: "12px", cursor: "pointer" },
  embeddedFormBlock: { padding: "24px", backgroundColor: "#f8fafc", border: "1px solid #e6f0fa", borderRadius: "12px", marginBottom: "24px" },
  formInlineInput: { width: "100%", padding: "11px 14px", border: "1px solid #cbd5e1", borderRadius: "8px", backgroundColor: "#ffffff", fontSize: "13px", boxSizing: "border-box" },
  paginationRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "24px" },
  paginationButton: { padding: "7px 16px", border: "1px solid #cbd5e1", borderRadius: "8px", backgroundColor: "#ffffff", color: "#0a255c", fontSize: "12px", fontWeight: "600", cursor: "pointer", boxShadow: "0 1px 2px rgba(0,0,0,0.05)" },
  modalOverlay: { position: "fixed", top: 0, left: 0, width: "100vw", height: "100vh", backgroundColor: "rgba(10, 37, 92, 0.4)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000, backdropFilter: "blur(4px)" },
  modalContentBox: { width: "90%", maxWidth: "1200px", backgroundColor: "#ffffff", padding: "36px", borderRadius: "16px", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.3)" },
  closeModalCrossButton: { background: "none", border: "none", color: "#64748b", fontWeight: "700", cursor: "pointer", fontSize: "18px" },
  immersiveGalleryRowGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: "20px", width: "100%", padding: "10px 0" },
  galleryCardContainerFrame: { backgroundColor: "#ffffff", border: "1px solid #e6f0fa", borderRadius: "14px", overflow: "hidden", display: "flex", flexDirection: "column", boxShadow: "0 4px 6px -1px rgba(10,37,92,0.02), 0 2px 4px -1px rgba(10,37,92,0.01)" },
  galleryCardDisplayMediaFrame: { width: "100%", height: "125px", backgroundColor: "#f8fafc", borderBottom: "1px solid #e6f0fa", overflow: "hidden" },
  galleryContentFrameMetaRow: { padding: "14px 18px", display: "flex", justifyContent: "space-between", alignItems: "center", backgroundColor: "#ffffff" },
  galleryItemNomenclatureTitleLabel: { fontSize: "14px", fontWeight: "700", color: "#0a255c", fontFamily: "monospace", letterSpacing: "0.5px" },
  galleryEditIconTriggerButton: { padding: "5px 12px", border: "1px solid #cbd5e1", borderRadius: "6px", backgroundColor: "#ffffff", color: "#0066cc", fontSize: "11px", fontWeight: "700", cursor: "pointer" },
  toastContainer: { position: "fixed", top: "24px", left: "50%", transform: "translateX(-50%)", zIndex: 9999, pointerEvents: "none" },
  toastCard: { backgroundColor: "#0a255c", color: "#ffffff", padding: "14px 28px", borderRadius: "6px", display: "flex window", alignItems: "center", boxShadow: "0 20px 25px -5px rgba(0,0,0,0.15)", borderLeft: "4px solid #0066cc", fontSize: "13px", fontWeight: "500" }
};